//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Code
    {
        public string companyCode { get; set; }
        public string initial { get; set; }
        public string companyName { get; set; }
        public string status { get; set; }
        public string dibuatOleh { get; set; }
        public Nullable<System.DateTime> dibuatTanggal { get; set; }
        public string diubahOleh { get; set; }
        public Nullable<System.DateTime> diubahTanggal { get; set; }
    }
}
