//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMPR
    {
        public int IDROW { get; set; }
        public string PRSAP { get; set; }
        public Nullable<System.DateTime> TGLPRSAP { get; set; }
        public string ATMT { get; set; }
        public Nullable<System.DateTime> TGLRELEASEPR { get; set; }
        public string TYPEUNIT { get; set; }
        public string YEAR { get; set; }
    }
}
