//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMBPKB
    {
        public string PONUMBER { get; set; }
        public Nullable<System.DateTime> TGLPROMISEDELIVERYBPKB { get; set; }
        public Nullable<System.DateTime> ACTUALRECEIVEDBPKBDICAB { get; set; }
        public Nullable<System.DateTime> ACTUALRECEIVEDBPKBDIHO { get; set; }
        public string DETAILPROBLEM { get; set; }
        public Nullable<System.DateTime> DELIVERYDATEBPKB { get; set; }
        public string KETSURATUBAHBENTUK { get; set; }
        public string KETBPKB { get; set; }
        public string KETKAROSERI { get; set; }
        public string LOKASIBPKB { get; set; }
        public string NOFAKTUR { get; set; }
        public string NOFORMULIRA { get; set; }
        public string NOSERTIFIKAT { get; set; }
        public string NOSURATUBAHBENTUK { get; set; }
        public string NOSERTIFIKATREGUJITIPE { get; set; }
        public string NOBPKB { get; set; }
        public string NOPOLISI { get; set; }
        public string POSISIBPKB { get; set; }
        public string PROGRESBPKB { get; set; }
        public string STATUSBPKB { get; set; }
        public Nullable<System.DateTime> TGLFAKTUR { get; set; }
        public Nullable<System.DateTime> TGLFORMULIRA { get; set; }
        public Nullable<System.DateTime> TGLSERAHBPKB { get; set; }
        public Nullable<System.DateTime> TGLSERTIFIKAT { get; set; }
        public Nullable<System.DateTime> TGLSURATUBAHBENTUK { get; set; }
        public Nullable<System.DateTime> TGLGRBPKB { get; set; }
        public Nullable<System.DateTime> TGLSTNK { get; set; }
        public Nullable<System.DateTime> TGLBPKBDIKIRIMKEMBALI { get; set; }
        public Nullable<System.DateTime> ACTUALDELIVERYBPKBTOFINANCE { get; set; }
        public Nullable<System.DateTime> DATEDELIVERYTOBRANCHORVENDOR { get; set; }
        public string REMARKSDETAILPROBLEM { get; set; }
        public Nullable<System.DateTime> ACTUALRECEIVEDBPKBHOBACK { get; set; }
        public Nullable<System.DateTime> STCKDATE { get; set; }
        public string NOPOLISI_INPUT { get; set; }
        public Nullable<System.DateTime> TGLSTNK_INPUT { get; set; }
        public string REASONREVISEBPKB { get; set; }
        public Nullable<System.DateTime> REVISEDATE { get; set; }
        public Nullable<bool> isRevised { get; set; }
        public string NOSURATRUBAHWARNA { get; set; }
        public Nullable<System.DateTime> TANGGALSURATRUBAHWARNA { get; set; }
        public string KETERANGANSURATRUBAHWARNA { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
