//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_S02001_TEMP_HS
    {
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<decimal> Version { get; set; }
        public string CustomerNumber { get; set; }
        public string KodeCabangAI { get; set; }
        public string MaterialNumberSERA { get; set; }
        public string MaterialDescriptionSERA { get; set; }
        public string MaterialNumberAI { get; set; }
        public string ColorDescSERA { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string NamaKaroseri { get; set; }
        public string AlamatKaroseri { get; set; }
        public string PIC { get; set; }
        public string NoTelepon { get; set; }
        public string BentukKaroseri { get; set; }
        public Nullable<System.DateTime> InfoPromiseDelivery { get; set; }
        public string CustomerSTNKName { get; set; }
        public Nullable<int> Title { get; set; }
        public string Address { get; set; }
        public string KTPTDP { get; set; }
        public string PostalCode { get; set; }
        public string PartnerName { get; set; }
        public string PartnerAddress { get; set; }
        public string Telepon { get; set; }
        public string City { get; set; }
        public string RegionCode { get; set; }
        public string PartnerPostalCode { get; set; }
        public Nullable<double> Diskon { get; set; }
        public Nullable<double> Pricing { get; set; }
        public string CurrencyCode { get; set; }
        public string CompanyCodeAI { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
    }
}
