//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_DOWNLOAD_TRANSACTIONDATADETAIL
    {
        public int ID { get; set; }
        public int TransactionDataID { get; set; }
        public string Data { get; set; }
    }
}
