//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_S02007_TEMP
    {
        public string PONUMBER { get; set; }
        public Nullable<int> VERSIONPOSERA { get; set; }
        public string BILLINGNO { get; set; }
        public Nullable<System.DateTime> INVOICERECEIPTDATE { get; set; }
        public Nullable<int> DATAVERSION { get; set; }
        public string CompanyCodeAI { get; set; }
        public Nullable<System.DateTime> payPlan { get; set; }
    }
}
