//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMMISC
    {
        public string PONumber { get; set; }
        public string MatDoc { get; set; }
        public Nullable<System.DateTime> ItemDelvDate { get; set; }
        public string ClearingDocNumber { get; set; }
        public string AccDocNumber { get; set; }
        public string FlagDelete { get; set; }
        public string ReasonRejection { get; set; }
    }
}
