//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMCITY
    {
        public string CITYID { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string DIBUATOLEH { get; set; }
        public Nullable<System.DateTime> DIBUATTGL { get; set; }
        public string DIUBAHOLEH { get; set; }
        public Nullable<System.DateTime> DIUBAHTGL { get; set; }
    }
}
