//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_S02002
    {
        public int ID { get; set; }
        public Nullable<int> TransactionDataID { get; set; }
        public string PONumber { get; set; }
        public Nullable<decimal> VersionPOSERA { get; set; }
        public Nullable<decimal> DataVersion { get; set; }
        public string StatusPOSERA { get; set; }
        public string RejectRevisedPOSERA { get; set; }
        public string DocumentNo { get; set; }
        public string AIMaterialNumber { get; set; }
        public string SERAMaterialNumber { get; set; }
        public string SERAMaterialDescription { get; set; }
        public string AIColor { get; set; }
        public string SERAColor { get; set; }
        public string QuotationNo { get; set; }
        public string SalesOrderNo { get; set; }
        public Nullable<bool> SalesOrderStatus { get; set; }
        public Nullable<double> DPPByVendor { get; set; }
        public Nullable<double> PPNByVendor { get; set; }
        public Nullable<double> BBNPriceByVendor { get; set; }
        public string Currency { get; set; }
        public string ChassisNumberByVendor { get; set; }
        public string MachineNumberByVendor { get; set; }
        public string CBUCKD { get; set; }
        public Nullable<int> Year { get; set; }
        public string FactureDONumber { get; set; }
        public Nullable<bool> BillingStatus { get; set; }
        public Nullable<System.DateTime> FactureDODate { get; set; }
        public string NoFakturKendaraan { get; set; }
        public Nullable<System.DateTime> TanggalFakturKendaraan { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<System.DateTime> ActualDateDeliveryUnit { get; set; }
        public string BSTKBNo { get; set; }
        public string LicensePlateByVendor { get; set; }
        public Nullable<System.DateTime> STNKDateByVendor { get; set; }
        public Nullable<System.DateTime> RevisiSTNK { get; set; }
        public string NoSertifikat { get; set; }
        public Nullable<System.DateTime> TglSertifikat { get; set; }
        public string NoFormulirA { get; set; }
        public Nullable<System.DateTime> TglFormulirA { get; set; }
        public string NoSertifikatRegUjiTipe { get; set; }
        public Nullable<System.DateTime> ActualDeliveryBPKBDate { get; set; }
        public string NamaPenerima { get; set; }
        public string AlamatPenerima { get; set; }
        public string BPKBNumber { get; set; }
        public string RemarksBPKB { get; set; }
        public Nullable<System.DateTime> RevisiBPKB { get; set; }
        public string dibuatOleh { get; set; }
        public Nullable<System.DateTime> dibuatTanggal { get; set; }
        public string diubahOleh { get; set; }
        public Nullable<System.DateTime> diubahTanggal { get; set; }
        public string xmlStatus { get; set; }
        public string xmlCreatedBy { get; set; }
        public Nullable<System.DateTime> xmlCreatedDate { get; set; }
        public string xmlModifiedBy { get; set; }
        public Nullable<System.DateTime> xmlModifiedDate { get; set; }
    }
}
