//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMPO
    {
        public string PONUMBER { get; set; }
        public Nullable<System.DateTime> TGLPO { get; set; }
        public string PRNUMBERSAP { get; set; }
        public Nullable<double> HARGAOPTIONAL { get; set; }
        public Nullable<System.DateTime> TGLKIRIMCABVENDOR { get; set; }
        public string KETPO { get; set; }
        public string PPNOPTIONAL { get; set; }
        public string CABANGVENDOR { get; set; }
        public string DESCCHANGEPO { get; set; }
        public string DESCPO { get; set; }
        public Nullable<double> DISC { get; set; }
        public Nullable<double> HARGABBN { get; set; }
        public Nullable<double> HARGADPP { get; set; }
        public Nullable<double> HARGAPPNUNIT { get; set; }
        public string MAINTYPEUNIT { get; set; }
        public Nullable<double> PRICELIST { get; set; }
        public Nullable<System.DateTime> PROMISEDLVDATEPO { get; set; }
        public Nullable<System.DateTime> TGLCHANGEPO { get; set; }
        public string VENDORID { get; set; }
        public string VENDORNAME { get; set; }
        public Nullable<double> BIAYAPENGIRIMAN { get; set; }
        public string CITY { get; set; }
        public string BENTUKAKHIRUNIT { get; set; }
        public string HISTORYPO { get; set; }
        public Nullable<System.DateTime> TGLMASUKKAROSERI { get; set; }
        public Nullable<System.DateTime> TGLSELESAIKAROSERI { get; set; }
        public string PURCHASESTATUS { get; set; }
        public string POSTATUSID { get; set; }
        public Nullable<double> ONTHEROADPRICE { get; set; }
        public Nullable<System.DateTime> EXPECTEDDATEDELIVERED { get; set; }
        public string COLOR { get; set; }
        public string UNITDELIVERYADDRESS { get; set; }
        public Nullable<System.DateTime> ACTUALDATEDELIVEREDUNIT { get; set; }
        public string REMARKSPOVENDOR { get; set; }
        public string REMARKSCARROSSERIE { get; set; }
        public Nullable<System.DateTime> ACTUALRECEIVEDBPKBHOFROMBRANCH { get; set; }
        public Nullable<double> DELIVERYCOST { get; set; }
        public string CARROSERIEVENDORNAME { get; set; }
        public string ACCESORIESADDRESS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> DODATE { get; set; }
        public string DONUMBER { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<double> HARGABBN_INPUT { get; set; }
        public Nullable<double> HARGADPP_INPUT { get; set; }
        public Nullable<double> HARGAPPNUNIT_INPUT { get; set; }
        public string CARMODEL { get; set; }
        public string CARSERIES { get; set; }
        public string COMPANYCODE { get; set; }
        public string COMPANYNAME { get; set; }
        public string ATMT { get; set; }
        public string KODECABANG { get; set; }
        public string CABANGTRAC { get; set; }
        public string MERK { get; set; }
        public string TYPEUNIT { get; set; }
        public string VARIAN { get; set; }
        public string VARIAN_INPUT { get; set; }
        public string MERK_INPUT { get; set; }
        public Nullable<int> POQTY { get; set; }
        public string PRSAP { get; set; }
        public string REASONREVISEDBYVENDOR { get; set; }
        public Nullable<System.DateTime> REVISEDDATE { get; set; }
        public Nullable<bool> isRevised { get; set; }
        public Nullable<System.DateTime> TGLGI { get; set; }
        public string RefDocNo { get; set; }
        public string CODEGROUP { get; set; }
        public Nullable<decimal> TOTALPAYMENT { get; set; }
        public Nullable<decimal> LOCALPRICE { get; set; }
        public string CURRENCY { get; set; }
        public string CLIENT { get; set; }
        public string FISCALYEAR { get; set; }
        public string PROPOSALNUMBER { get; set; }
        public string ITEM { get; set; }
        public Nullable<System.DateTime> APPROVALDATETIME { get; set; }
        public Nullable<int> flagRejection { get; set; }
        public string PICKAROSERI { get; set; }
        public string NOTELEPONKAROSERI { get; set; }
        public string BENTUKKAROSERI { get; set; }
        public string SHIPPINGADDRESS1 { get; set; }
        public string SHIPPINGADDRESS2 { get; set; }
        public string SHIPPINGADDRESS3 { get; set; }
        public string SHIPPINGADDRESS4 { get; set; }
        public string BBNADDRESS1 { get; set; }
        public string BBNADDRESS2 { get; set; }
        public string BBNADDRESS3 { get; set; }
        public string BBNADDRESS4 { get; set; }
        public Nullable<System.DateTime> xmlModifiedDate { get; set; }
        public string xmlModifiedBy { get; set; }
        public Nullable<System.DateTime> xmlCreatedDate { get; set; }
        public string xmlCreatedBy { get; set; }
        public string xmlStatus { get; set; }
        public string updateqty { get; set; }
        public string materialnumber { get; set; }
    }
}
