//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_VENDOR_TRANSACTION
    {
        public string PONumber { get; set; }
        public Nullable<int> VersionPOSERA { get; set; }
        public Nullable<int> DataVersion { get; set; }
        public string StatusPOSERA { get; set; }
        public string RejectRevisedPOSERA { get; set; }
        public string DocumentNo { get; set; }
        public string AIMaterialNumber { get; set; }
        public string SERAMaterialNumber { get; set; }
        public string SERAMaterialDescription { get; set; }
        public string AIColor { get; set; }
        public string SERAColor { get; set; }
        public string QuotationNo { get; set; }
        public string SalesOrderNo { get; set; }
        public Nullable<bool> SalesOrderStatus { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> BillingStatus { get; set; }
        public string CancellationReason { get; set; }
        public string BSTKBNo { get; set; }
        public Nullable<System.DateTime> RevisiSTNK { get; set; }
        public string NamaPenerima { get; set; }
        public string AlamatPenerima { get; set; }
        public string StatusCancel { get; set; }
        public string ReasonRejection { get; set; }
        public Nullable<decimal> AmountKuitansiDC { get; set; }
        public string BusinessAreaCode { get; set; }
        public string CustomerNo { get; set; }
        public string NomorSpes { get; set; }
        public string SalesmanNumber { get; set; }
        public string KuitansiNoRef { get; set; }
        public Nullable<System.DateTime> KuitansiDateRef { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
