//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_S02006
    {
        public int ID { get; set; }
        public Nullable<int> TransactionDataID { get; set; }
        public string BillingNo { get; set; }
        public string KuitansiNo { get; set; }
        public Nullable<System.DateTime> KuitansiDate { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> AmountKuitansiDC { get; set; }
        public string BusinessAreaCode { get; set; }
        public string CustomerNo { get; set; }
        public string NomorSpes { get; set; }
        public string SalesOrderNo { get; set; }
        public string SalesmanNumber { get; set; }
        public string NomorFakturPajak { get; set; }
        public string ChasisNumber { get; set; }
        public string PONumberSERA { get; set; }
        public Nullable<decimal> VersionPOSERA { get; set; }
        public string KuitansiNoRef { get; set; }
        public Nullable<System.DateTime> KuitansiDateRef { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string dibuatOleh { get; set; }
        public Nullable<System.DateTime> dibuatTanggal { get; set; }
        public string diubahOleh { get; set; }
        public Nullable<System.DateTime> diubahTanggal { get; set; }
        public string xmlStatus { get; set; }
        public string xmlCreatedBy { get; set; }
        public Nullable<System.DateTime> xmlCreatedDate { get; set; }
        public string xmlModifiedBy { get; set; }
        public Nullable<System.DateTime> xmlModifiedDate { get; set; }
    }
}
