//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMIR
    {
        public string PONUMBER { get; set; }
        public Nullable<System.DateTime> ACTUALRECEIVEDINV { get; set; }
        public string HARGADELIVERYAP { get; set; }
        public Nullable<System.DateTime> INVDATE { get; set; }
        public string INVNO { get; set; }
        public string KETBAYAR { get; set; }
        public string NOFAKTURPAJAK { get; set; }
        public Nullable<System.DateTime> TGLSERAHTAGIHAN { get; set; }
        public Nullable<int> TERMOFPAYMENT { get; set; }
        public string NOAP { get; set; }
        public Nullable<System.DateTime> TGLPEMBAYARAN { get; set; }
        public string KETTAGIHAN { get; set; }
        public Nullable<System.DateTime> ESTIMATEDPAYMENTDATE { get; set; }
        public string INVOICESTATUS { get; set; }
        public string REASONREJECTIONINVOICE { get; set; }
        public string BPHNUMBER { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> REVISEDATE { get; set; }
        public Nullable<bool> isRevised { get; set; }
        public string xmlStatus { get; set; }
        public string xmlCreatedBy { get; set; }
        public Nullable<System.DateTime> xmlCreatedDate { get; set; }
        public string xmlModifiedBy { get; set; }
        public Nullable<System.DateTime> xmlModifiedDate { get; set; }
        public Nullable<System.DateTime> xmlModifiedDateInvNo { get; set; }
        public string xmlModifiedByInvNo { get; set; }
        public Nullable<System.DateTime> xmlCreatedDateInvNo { get; set; }
        public string xmlCreatedByInvNo { get; set; }
        public Nullable<System.DateTime> xmlModifiedDateFaktur { get; set; }
        public string xmlModifiedByFaktur { get; set; }
        public Nullable<System.DateTime> xmlCreatedDateFaktur { get; set; }
        public string xmlCreatedByFaktur { get; set; }
        public string xmlStatusInvNo { get; set; }
        public string xmlStatusByEngine { get; set; }
    }
}
