//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMGR
    {
        public string PONUMBER { get; set; }
        public Nullable<System.DateTime> ACTUALRECEIVEDUNIT { get; set; }
        public string NOCHASIS { get; set; }
        public string NOENGINE { get; set; }
        public string NOEQUIP { get; set; }
        public string NOEQUIPBARU { get; set; }
        public Nullable<System.DateTime> TGLCREATEEQUIP { get; set; }
        public Nullable<System.DateTime> TGLGRSAP { get; set; }
        public string NAMAPEMILIK { get; set; }
        public string VENDORNAMEAP { get; set; }
        public string STATUSDELIVERYUNIT { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> ACTUALRECEIVEDUNITINBDEL { get; set; }
        public string NOCHASIS_INPUT { get; set; }
        public string NOENGINE_INPUT { get; set; }
        public string NAMAPEMILIK_INPUT { get; set; }
        public string xmlStatus { get; set; }
        public string xmlCreatedBy { get; set; }
        public Nullable<System.DateTime> xmlCreatedDate { get; set; }
        public string xmlModifiedBy { get; set; }
        public Nullable<System.DateTime> xmlModifiedDate { get; set; }
        public string xmlStatusEngine { get; set; }
        public Nullable<System.DateTime> xmlModifiedDateEngine { get; set; }
        public string xmlModifiedByEngine { get; set; }
        public Nullable<System.DateTime> xmlCreatedDateEngine { get; set; }
        public string xmlCreatedByEngine { get; set; }
    }
}
