//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_LOG
    {
        public int ID { get; set; }
        public string WebServiceName { get; set; }
        public string MethodName { get; set; }
        public bool Acknowledge { get; set; }
        public string TicketNo { get; set; }
        public string Message { get; set; }
        public string FileType { get; set; }
        public string CreatedWho { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public string ChangedWho { get; set; }
        public System.DateTime ChangedWhen { get; set; }
    }
}
