//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_S02001_TEMP_IS
    {
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<int> DataVersion { get; set; }
        public string AccessoriesNumberAI { get; set; }
        public string AccessoriesNumberSERA { get; set; }
        public string AccessoriesDescriptionSERA { get; set; }
        public Nullable<decimal> QtyAccessories { get; set; }
        public string CompanyCodeAI { get; set; }
    }
}
