//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOM_S02009_TEMP_HS
    {
        public int ID { get; set; }
        public Nullable<int> TransactionDataID { get; set; }
        public string PONumber { get; set; }
        public Nullable<decimal> VersionPOSERA { get; set; }
        public Nullable<decimal> DataVersion { get; set; }
        public string CompanyCodeAI { get; set; }
        public string KodeCabangAI { get; set; }
        public string dibuatOleh { get; set; }
        public Nullable<System.DateTime> dibuatTanggal { get; set; }
        public string diubahOleh { get; set; }
        public Nullable<System.DateTime> diubahTanggal { get; set; }
    }
}
