//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMCOMPANY
    {
        public string COMPANYCODE { get; set; }
        public string COMPANYNAME { get; set; }
        public string ALAMAT { get; set; }
        public string KOTA { get; set; }
        public string REGION { get; set; }
        public string POSTALCODE { get; set; }
        public string TELEPON { get; set; }
        public string NPWP { get; set; }
        public string KTPTDP { get; set; }
        public string COMPANYCODETSO { get; set; }
        public string COMPANYCODEDSO { get; set; }
        public string COMPANYCODEISO { get; set; }
        public string DIBUATOLEH { get; set; }
        public Nullable<System.DateTime> DIBUATTGL { get; set; }
        public string DIUBAHOLEH { get; set; }
        public Nullable<System.DateTime> DIUBAHTGL { get; set; }
    }
}
