//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMSERATOAI
    {
        public string PONUMBER { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string CURRENCYCODE { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
