//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Aktifitas
    {
        public string User_ID { get; set; }
        public System.DateTime TGL_Aktifitas { get; set; }
        public string MenuName { get; set; }
        public string Alamat_IP { get; set; }
        public string Catatan { get; set; }
    }
}
