//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_User
    {
        public System.Guid ID { get; set; }
        public string UserID { get; set; }
        public string FullName { get; set; }
        public string GroupID { get; set; }
        public string RegionID { get; set; }
        public string Group_VendorID { get; set; }
        public string id_vendor { get; set; }
        public string Password { get; set; }
        public Nullable<int> CountError { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<bool> NeverExpired { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<decimal> No_Telp { get; set; }
        public string Email { get; set; }
        public string PLANTID { get; set; }
    }
}
