//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Vendor
    {
        public string id_vendor { get; set; }
        public string nama_vendor { get; set; }
        public string alamat_vendor { get; set; }
        public string city { get; set; }
        public Nullable<decimal> telp_vendor { get; set; }
        public Nullable<decimal> status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUser { get; set; }
        public string LastIP { get; set; }
    }
}
