//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSMATERIAL
    {
        public string MATERIALNUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string MATERIALTYPE { get; set; }
        public string MATERIALGROUP { get; set; }
        public string OLDMATERIAL { get; set; }
        public string BOMMATERIAL { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public string GARDAN { get; set; }
        public string YEAR { get; set; }
        public string PURCHASEGROUPID { get; set; }
        public string MATERIALIDVENDOR { get; set; }
        public Nullable<double> PRICELIST { get; set; }
    }
}
