//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSPLANT
    {
        public string PLANTID { get; set; }
        public string NAME { get; set; }
        public string ALAMAT { get; set; }
        public string KELURAHAN { get; set; }
        public string KECAMATAN { get; set; }
        public string CITY { get; set; }
        public string REGION { get; set; }
        public string CONTACTPERSONNAME { get; set; }
        public string ALAMAT2 { get; set; }
        public string ALAMAT3 { get; set; }
        public string ALAMAT4 { get; set; }
        public string ALAMAT5 { get; set; }
        public string PROPINSI { get; set; }
        public string PIC { get; set; }
        public string TITLECP { get; set; }
        public string NOHPCP { get; set; }
        public string NOTELPPLANT { get; set; }
        public string POSTALCODE { get; set; }
        public string CUSTOMERNO { get; set; }
    }
}
