//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSSTORAGELOCATION
    {
        public long ID { get; set; }
        public string COMPANYCODE { get; set; }
        public string STORAGELOCATIONID { get; set; }
        public string SLOCDESCRIPTION { get; set; }
        public string PLANTID { get; set; }
        public string PLANTDESCRIPTION { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string POSTALCODE { get; set; }
    }
}
