//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMINDER_LOG
    {
        public string PONUMBER { get; set; }
        public string POSTATUS { get; set; }
        public System.DateTime LASTMAILDATE { get; set; }
    }
}
