//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLUSER
    {
        public int ID { get; set; }
        public string NRP { get; set; }
        public string USERNAME { get; set; }
        public string JOBROLEKEY { get; set; }
        public string JOBROLEDESC { get; set; }
        public string JOBPOSITIONKEY { get; set; }
        public string JOBPOSITIONDESC { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public string COMPANYCODE { get; set; }
        public string SALESOFFICE { get; set; }
        public string SALESGROUP { get; set; }
        public string FULLNAME { get; set; }
        public string SIGNATUREPATH { get; set; }
        public string SMREFERENCE { get; set; }
        public string REPORTINGNAME { get; set; }
        public string STATUS { get; set; }
    }
}
