//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREAMLINER
    {
        public int ID { get; set; }
        public string SalesContractNumber { get; set; }
        public Nullable<System.DateTime> SalesContractDate { get; set; }
        public Nullable<System.DateTime> PRDeliveryDate { get; set; }
        public string RequesterName { get; set; }
        public string PRStatus { get; set; }
        public string PRKaroseri { get; set; }
        public string PRAccessories { get; set; }
        public string ProcessVKaroseri { get; set; }
        public string ProcessVAccs { get; set; }
        public Nullable<System.DateTime> PROMISEDLVDATEPO { get; set; }
        public string PeriodePO { get; set; }
        public string OfficerName { get; set; }
        public string POStatus { get; set; }
        public string BBN { get; set; }
        public string Merk { get; set; }
        public string BentukAkhirUnit { get; set; }
        public string Gardan { get; set; }
        public Nullable<System.DateTime> EXPECTEDDATEDELIVERED { get; set; }
        public string Plant { get; set; }
        public string PRType { get; set; }
        public Nullable<System.DateTime> REQUESTDELIVERYDATE { get; set; }
        public Nullable<System.DateTime> PRDATEASSIGNMENT { get; set; }
        public string ItemDoc { get; set; }
        public string DocType { get; set; }
        public string VendorAccountNumber { get; set; }
        public string MatGroup { get; set; }
        public string DocCond { get; set; }
        public string UoM { get; set; }
        public string InfoRecord { get; set; }
        public string CurrDisc { get; set; }
        public string CurrBBN { get; set; }
        public string CurrDPP { get; set; }
        public Nullable<double> DLCPrice { get; set; }
        public string CurrDLC { get; set; }
        public string CurrPPN { get; set; }
        public Nullable<double> NetPrice { get; set; }
        public string CurrOPT { get; set; }
        public Nullable<decimal> DocPrice { get; set; }
        public string ItemText { get; set; }
        public string TextLine2 { get; set; }
        public string TextLine3 { get; set; }
        public string TextLine4 { get; set; }
        public string TextLine5 { get; set; }
        public string TextLine6 { get; set; }
        public string TextLine7 { get; set; }
        public string TextLine8 { get; set; }
        public string TextLine9 { get; set; }
        public string TextLine10 { get; set; }
        public string TextLine11 { get; set; }
        public string CurrNetprInfRec { get; set; }
        public string CarDesc { get; set; }
        public Nullable<decimal> MatDocItem { get; set; }
        public string FiscalYear { get; set; }
        public string matdocGI { get; set; }
        public string ManSerialNumber { get; set; }
        public string AssetNumber { get; set; }
        public string CarRBentuk { get; set; }
        public Nullable<System.DateTime> DateCarRBentuk { get; set; }
        public string CarFaktur { get; set; }
        public Nullable<System.DateTime> DateCarFaktur { get; set; }
        public string CarFormA { get; set; }
        public Nullable<System.DateTime> DateCarFormA { get; set; }
        public string CarSertif { get; set; }
        public Nullable<System.DateTime> DateCarSertif { get; set; }
        public string CarRegUji { get; set; }
        public string CarBPKB { get; set; }
        public string StatusCarBPKB { get; set; }
        public string RefKey { get; set; }
        public string PONUMBER { get; set; }
        public string Customername { get; set; }
        public Nullable<decimal> SchedItem { get; set; }
        public Nullable<System.DateTime> SchedDelvDate { get; set; }
        public string TujuanDeliveryUnit { get; set; }
        public string Approver { get; set; }
    }
}
