//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOAD_FILE
    {
        public string PONUMBER { get; set; }
        public Nullable<System.DateTime> TGLPO { get; set; }
        public string KET { get; set; }
        public string FILE { get; set; }
        public string LASTUSER { get; set; }
        public Nullable<System.DateTime> LASTDATE { get; set; }
    }
}
