//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCGenerateXMLService__NonB2B.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_GROUP
    {
        public long ID { get; set; }
        public string Group_VendorID { get; set; }
        public string Group_VendorName { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modified_BY { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
